[plugin]
prepend_previewers = [
  { mime = "text/*", run = "code", max_size = 524288 },  # syntax highlight up to 512KB
  { mime = "text/*", run = "noop" },                     # large text files
  { url  = "*/",    run = "folder" },                    # directories
  { mime = "*/*",   run = "noop" },                      # everything else
]

[opener]
open-okular = [
  { run = "okular %s", orphan = true, desc = "Okular" },
]
open-evince = [
  { run = "evince %s", orphan = true, desc = "Document Viewer" },
]
open-inkscape = [
  { run = "inkscape %s", orphan = true, desc = "Inkscape" },
]
open-eog = [
  { run = "eog %s", orphan = true, desc = "Image Viewer" },
]

[open]
prepend_rules = [
  { mime = "image/svg+xml", use = ["open-inkscape", "open-eog"] },
  { mime = "application/pdf", use = ["open-evince", "open-okular"] },
]
